name: 'Deploy'
on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
jobs:
  deploy:
    name: 'Deploy to prod'
    environment: Production
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.2.0
      - name: 'Tailscale'
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
          args: --ssh
      - name: Deploy
        id: deploy
        if: steps.tailscale.outcome == 'success'
        run: ssh -o StrictHostKeyChecking=no "$SSH_USER"@"$SSH_HOST" 'cd infra && git pull --ff-only && docker-compose down && docker-compose up --force-recreate -d'
        env:
           SSH_HOST: ${{ secrets.SSH_HOST }}
           SSH_USER: ${{ secrets.SSH_USER }}
      - name: Logout
        run: sudo tailscale logout
