name: 'Deploy'
on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
jobs:
  deploy:
    name: 'Deploy to prod'
    environment: Production
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.2.0
      - name: 'Tailscale'
        id: tailscale
        uses: tailscale/github-action@ce41a99162202a647a4b24c30c558a567b926709
        with:
          version: 1.32.2
          authkey: ${{ secrets.TAILSCALE_AUTH_KEY }}
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_DNSIMPLE_OAUTH_TOKEN: ${{ secrets.DNSIMPLE_OAUTH_TOKEN }}
          envkey_DOMAINNAME: ${{ secrets.DOMAINNAME }}
          envkey_LOCAL_IP: ${{ secrets.LOCAL_IP }}
          envkey_MEDIA_PATH: ${{ secrets.MEDIA_PATH }}
          envkey_MEDIA_PATH_V2: ${{ secrets.MEDIA_PATH_V2 }}
          envkey_PGID: ${{ secrets.PGID }}
          envkey_PIHOLE_PASSWORD: ${{ secrets.PIHOLE_PASSWORD }}
          envkey_PUID: ${{ secrets.PUID }}
          envkey_TZ: ${{ secrets.TZ }}
          envkey_USERDIR: ${{ secrets.USERDIR }}
          envkey_LIBRESPEED_PASSWORD: ${{ secrets.LIBRESPEED_PASSWORD }}
      - name: Add SSH key
        id: ssh
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          MACHINE_IP="$(tailscale ip -6 $MACHINE)"
          ssh-keyscan $MACHINE_IP >> ~/.ssh/known_hosts
      - name: 'Docker Deploy'
        id: docker-deploy
        uses: chaplyk/docker-compose-remote-action@v1.1
        with:
          ssh_host: ${{ secrets.SSH_HOST }}
          ssh_user: ${{ secrets.SSH_USER }}
          ssh_key: ${{ secrets.SSH_KEY }}
          compose_file: docker-compose.yml
          pull: true
          build: true
      - name: Logout
        run: sudo tailscale logout
